"""
Formal verification model export for the Lattice Transfer Protocol.

Generates syntactically valid Tamarin Prover and ProVerif models encoding
the LTP three-phase protocol (COMMIT / LATTICE / MATERIALIZE) and its
security properties (Theorems 3-8 from the whitepaper).

These models are stubs suitable for feeding into Tamarin/ProVerif for
automated security analysis. They encode the protocol's message flow
and adversary model but use symbolic cryptography (not computational).

Reference:
  - Tamarin Prover: https://tamarin-prover.com (ETH Zurich)
  - ProVerif: https://bblanche.gitlabpages.inria.fr/proverif/ (INRIA)
  - Whitepaper §3.3: Formal security definitions (Theorems 3-8)
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Optional

__all__ = [
    "VerificationProperty",
    "TamarinModel",
    "ProVerifModel",
]


class VerificationProperty(Enum):
    """
    Security properties from the whitepaper, mapped to formal verification lemmas.

    Each property corresponds to a game-based security definition in §3.3.
    """
    IMM = "immutability"          # Theorem 3: Entity immutability
    SINT = "shard_integrity"      # Theorem 4: Shard integrity
    TCONF = "transfer_conf"       # Theorem 5: Transfer confidentiality
    NREP = "non_repudiation"      # Theorem 6: Non-repudiation
    TSEC = "threshold_secrecy"    # Theorem 7: Threshold secrecy
    TIMM = "transfer_immutab"     # Theorem 8: Transfer immutability

    @property
    def whitepaper_ref(self) -> str:
        refs = {
            "immutability": "§3.3.1 Theorem 3",
            "shard_integrity": "§3.3.2 Theorem 4",
            "transfer_conf": "§3.3.3 Theorem 5",
            "non_repudiation": "§3.3.4 Theorem 6",
            "threshold_secrecy": "§3.3.5 Theorem 7",
            "transfer_immutab": "§3.3.6 Theorem 8",
        }
        return refs[self.value]

    @property
    def machine_checkable(self) -> bool:
        """Whether this property can be fully machine-checked in Tamarin/ProVerif."""
        return self in (
            VerificationProperty.IMM,
            VerificationProperty.TCONF,
            VerificationProperty.NREP,
            VerificationProperty.TIMM,
        )


class TamarinModel:
    """Exports LTP protocol model in Tamarin Prover syntax."""

    @staticmethod
    def export(
        properties: list[VerificationProperty] | None = None,
        include_adversary: bool = True,
    ) -> str:
        """Generate a complete Tamarin model for the LTP protocol."""
        props = properties or list(VerificationProperty)
        lines = [
            "/*",
            " * LTP: Lattice Transfer Protocol — Tamarin Prover Model",
            " *",
            " * Auto-generated by ltp.verification",
            " * Reference: LTP Whitepaper §3.3",
            " *",
            " * Cryptographic primitives (symbolic):",
            " *   - H()     : collision-resistant hash function",
            " *   - aenc()  : ML-KEM encapsulation (modeled as asymmetric encryption)",
            " *   - sign()  : ML-DSA signature",
            " *   - senc()  : AEAD symmetric encryption",
            " */",
            "",
            "theory LTP_Protocol",
            'begin',
            "",
            "builtins: hashing, asymmetric-encryption, signing, symmetric-encryption",
            "",
            "/* ================================================================",
            "   Functions",
            "   ================================================================ */",
            "",
            "functions: erasure_encode/3, erasure_decode/3, entity_id/4",
            "",
            "/* entity_id = H(content, shape, timestamp, sender_vk) */",
            "equations: entity_id(content, shape, ts, vk) = h(<content, shape, ts, vk>)",
            "",
            "/* ================================================================",
            "   Protocol Rules — Three-Phase Transfer",
            "   ================================================================ */",
            "",
            "/* --- Key Generation --- */",
            "",
            "rule Generate_KeyPair:",
            "  [ Fr(~sk) ]",
            "  -->",
            "  [ !Ltk($A, ~sk), !Pk($A, pk(~sk)), Out(pk(~sk)) ]",
            "",
            "rule Generate_Signing_Key:",
            "  [ Fr(~sigk) ]",
            "  -->",
            "  [ !SignKey($A, ~sigk), !VerKey($A, verify_key(~sigk)), Out(verify_key(~sigk)) ]",
            "",
            "/* --- Phase 1: COMMIT --- */",
            "",
            "rule Commit:",
            "  let",
            "    eid = entity_id(content, shape, ts, verify_key(~sigk))",
            "    record = <eid, shard_root, shape, ts>",
            "    sig = sign(record, ~sigk)",
            "  in",
            "  [ !SignKey($Sender, ~sigk),",
            "    Fr(~cek), Fr(~ts)",
            "  ]",
            "  --[ Committed($Sender, eid, content),",
            "      CommitRecord(eid, record, sig) ]->",
            "  [ St_Committed($Sender, eid, content, ~cek, record, sig),",
            "    CommitLog(eid, record, sig) ]",
            "",
            "/* --- Phase 2: LATTICE --- */",
            "",
            "rule Lattice:",
            "  let",
            "    lattice_key = <eid, ~cek, h(record)>",
            "    sealed = aenc(lattice_key, pk_receiver)",
            "  in",
            "  [ St_Committed($Sender, eid, content, ~cek, record, sig),",
            "    !Pk($Receiver, pk_receiver) ]",
            "  --[ Sealed($Sender, $Receiver, eid),",
            "      KeyDelivered(eid, $Receiver) ]->",
            "  [ St_Sealed($Sender, $Receiver, eid, sealed),",
            "    Out(sealed) ]",
            "",
            "/* --- Phase 3: MATERIALIZE --- */",
            "",
            "rule Materialize:",
            "  let",
            "    lattice_key = adec(sealed, ~sk)",
            "    eid = fst(lattice_key)",
            "    cek = fst(snd(lattice_key))",
            "    ref = snd(snd(lattice_key))",
            "  in",
            "  [ !Ltk($Receiver, ~sk),",
            "    In(sealed),",
            "    CommitLog(eid, record, sig),",
            "    !VerKey($Sender, vk) ]",
            "  --[ Materialized($Receiver, eid),",
            "      VerifiedSignature(eid, sig, vk),",
            "      Eq(ref, h(record)),",
            "      Eq(verify(sig, record, vk), true) ]->",
            "  [ St_Materialized($Receiver, eid) ]",
            "",
        ]

        if include_adversary:
            lines.extend([
                "/* ================================================================",
                "   Adversary Model",
                "   ================================================================ */",
                "",
                "/* Adversary can compromise long-term keys */",
                "rule Compromise_LTK:",
                "  [ !Ltk($A, ~sk) ]",
                "  --[ Compromised($A) ]->",
                "  [ Out(~sk) ]",
                "",
                "/* Adversary can read the commitment log (public) */",
                "rule Read_Log:",
                "  [ CommitLog(eid, record, sig) ]",
                "  --[ ]->",
                "  [ CommitLog(eid, record, sig), Out(<eid, record, sig>) ]",
                "",
            ])

        lines.extend([
            "/* ================================================================",
            "   Restrictions",
            "   ================================================================ */",
            "",
            "restriction Equality:",
            '  "All x y #i. Eq(x, y) @ #i ==> x = y"',
            "",
            "/* ================================================================",
            "   Security Lemmas",
            "   ================================================================ */",
            "",
        ])

        for prop in props:
            lines.extend(_tamarin_lemma(prop))
            lines.append("")

        lines.append("end")
        return "\n".join(lines)


def _tamarin_lemma(prop: VerificationProperty) -> list[str]:
    """Generate a Tamarin lemma for a security property."""
    if prop == VerificationProperty.IMM:
        return [
            "/* Theorem 3 (IMM): Entity immutability — content uniquely determines entity_id */",
            "lemma entity_immutability:",
            '  "All sender eid content1 content2 #i #j.',
            '     Committed(sender, eid, content1) @ #i',
            '   & Committed(sender, eid, content2) @ #j',
            '   ==> content1 = content2"',
        ]
    elif prop == VerificationProperty.SINT:
        return [
            "/* Theorem 4 (SINT): Shard integrity — tampered shards detected by AEAD */",
            "/* Note: SINT is partially modeled; full model requires AEAD tag verification */",
            "lemma shard_integrity [heuristic=S]:",
            '  "All receiver eid #i.',
            '     Materialized(receiver, eid) @ #i',
            '   ==> Ex sender content #j. Committed(sender, eid, content) @ #j & #j < #i"',
        ]
    elif prop == VerificationProperty.TCONF:
        return [
            "/* Theorem 5 (TCONF): Transfer confidentiality — adversary cannot learn content */",
            "lemma transfer_confidentiality:",
            '  "All sender receiver eid #i #j.',
            '     Sealed(sender, receiver, eid) @ #i',
            '   & Materialized(receiver, eid) @ #j',
            '   & not (Ex #c. Compromised(receiver) @ #c)',
            '   ==> not (Ex adversary #a. Materialized(adversary, eid) @ #a',
            '            & not (adversary = receiver))"',
        ]
    elif prop == VerificationProperty.NREP:
        return [
            "/* Theorem 6 (NREP): Non-repudiation — commitment record proves sender committed */",
            "lemma non_repudiation:",
            '  "All eid record sig #i.',
            '     CommitRecord(eid, record, sig) @ #i',
            '   ==> Ex sender content #j. Committed(sender, eid, content) @ #j & #j <= #i"',
        ]
    elif prop == VerificationProperty.TSEC:
        return [
            "/* Theorem 7 (TSEC): Threshold secrecy — <k shards reveal nothing */",
            "/* Note: Information-theoretic; cannot be fully expressed in Tamarin's ",
            "   symbolic model. This lemma captures the protocol-level invariant. */",
            "lemma threshold_secrecy [heuristic=S]:",
            '  "All receiver eid #i.',
            '     Materialized(receiver, eid) @ #i',
            '   ==> Ex #j. KeyDelivered(eid, receiver) @ #j & #j < #i"',
        ]
    elif prop == VerificationProperty.TIMM:
        return [
            "/* Theorem 8 (TIMM): Transfer immutability — materialized content matches committed */",
            "lemma transfer_immutability:",
            '  "All receiver eid #i.',
            '     Materialized(receiver, eid) @ #i',
            '   ==> Ex sender content #j. Committed(sender, eid, content) @ #j & #j < #i"',
        ]
    return []


class ProVerifModel:
    """Exports LTP protocol model in ProVerif syntax."""

    @staticmethod
    def export(
        properties: list[VerificationProperty] | None = None,
        include_adversary: bool = True,
    ) -> str:
        """Generate a complete ProVerif model for the LTP protocol."""
        props = properties or list(VerificationProperty)
        lines = [
            "(* LTP: Lattice Transfer Protocol — ProVerif Model *)",
            "(* Auto-generated by ltp.verification *)",
            "(* Reference: LTP Whitepaper §3.3 *)",
            "",
            "(* ================================================================",
            "   Type declarations",
            "   ================================================================ *)",
            "",
            "type skey.",
            "type pkey.",
            "type sigkey.",
            "type verkey.",
            "type nonce.",
            "type content.",
            "type entity_id.",
            "",
            "(* ================================================================",
            "   Cryptographic primitives (symbolic)",
            "   ================================================================ *)",
            "",
            "(* ML-KEM key encapsulation *)",
            "fun pk(skey): pkey.",
            "fun aenc(bitstring, pkey): bitstring.",
            "reduc forall m: bitstring, k: skey; adec(aenc(m, pk(k)), k) = m.",
            "",
            "(* ML-DSA digital signatures *)",
            "fun spk(sigkey): verkey.",
            "fun sign(bitstring, sigkey): bitstring.",
            "reduc forall m: bitstring, k: sigkey; getmess(sign(m, k)) = m.",
            "reduc forall m: bitstring, k: sigkey; checksign(sign(m, k), spk(k)) = m.",
            "",
            "(* AEAD symmetric encryption *)",
            "fun senc(bitstring, bitstring): bitstring.",
            "reduc forall m: bitstring, k: bitstring; sdec(senc(m, k), k) = m.",
            "",
            "(* Hash function (collision-resistant) *)",
            "fun hash(bitstring): bitstring.",
            "",
            "(* Entity ID construction *)",
            "fun make_eid(content, bitstring, nonce, verkey): entity_id.",
            "",
            "(* ================================================================",
            "   Events for security properties",
            "   ================================================================ *)",
            "",
            "event Committed(verkey, entity_id, content).",
            "event Sealed(verkey, pkey, entity_id).",
            "event Materialized(skey, entity_id).",
            "event KeyDelivered(entity_id, pkey).",
            "",
            "(* ================================================================",
            "   Channels",
            "   ================================================================ *)",
            "",
            "free c: channel.",
            "free log: channel.",
            "",
            "(* Secret content for secrecy queries *)",
            "free secret_content: content [private].",
            "",
        ]

        for prop in props:
            lines.extend(_proverif_query(prop))
            lines.append("")

        lines.extend([
            "(* ================================================================",
            "   Processes",
            "   ================================================================ *)",
            "",
            "(* Sender process: COMMIT + LATTICE *)",
            "let Sender(sigk: sigkey, receiver_pk: pkey) =",
            "  new ts: nonce;",
            "  new cek: bitstring;",
            "  let eid = make_eid(secret_content, hash(secret_content), ts, spk(sigk)) in",
            "  let record = (eid, hash(secret_content), ts) in",
            "  let sig = sign((record), sigk) in",
            "  event Committed(spk(sigk), eid, secret_content);",
            "  out(log, (eid, record, sig));",
            "  (* Phase 2: LATTICE *)",
            "  let lattice_key = (eid, cek, hash((record))) in",
            "  let sealed = aenc(lattice_key, receiver_pk) in",
            "  event Sealed(spk(sigk), receiver_pk, eid);",
            "  event KeyDelivered(eid, receiver_pk);",
            "  out(c, sealed).",
            "",
            "(* Receiver process: MATERIALIZE *)",
            "let Receiver(sk: skey, sender_vk: verkey) =",
            "  in(c, sealed: bitstring);",
            "  let (eid: entity_id, cek: bitstring, ref: bitstring) = adec(sealed, sk) in",
            "  in(log, (=eid, record: bitstring, sig: bitstring));",
            "  let =record = checksign(sig, sender_vk) in",
            "  if ref = hash(record) then",
            "  event Materialized(sk, eid).",
            "",
            "(* ================================================================",
            "   Main process",
            "   ================================================================ *)",
            "",
            "process",
            "  new sender_sigk: sigkey;",
            "  new receiver_sk: skey;",
            "  let sender_vk = spk(sender_sigk) in",
            "  let receiver_pk = pk(receiver_sk) in",
            "  out(c, sender_vk);",
            "  out(c, receiver_pk);",
            "  ( Sender(sender_sigk, receiver_pk) | Receiver(receiver_sk, sender_vk) )",
        ])

        return "\n".join(lines)


def _proverif_query(prop: VerificationProperty) -> list[str]:
    """Generate a ProVerif query for a security property."""
    if prop == VerificationProperty.IMM:
        return [
            "(* Theorem 3 (IMM): Entity immutability *)",
            "(* Content uniquely determines entity_id *)",
            "query vk: verkey, eid: entity_id, c1: content, c2: content;",
            "  event(Committed(vk, eid, c1)) && event(Committed(vk, eid, c2)) ==> c1 = c2.",
        ]
    elif prop == VerificationProperty.TCONF:
        return [
            "(* Theorem 5 (TCONF): Transfer confidentiality *)",
            "query attacker(secret_content).",
        ]
    elif prop == VerificationProperty.NREP:
        return [
            "(* Theorem 6 (NREP): Non-repudiation *)",
            "query sk: skey, eid: entity_id;",
            "  event(Materialized(sk, eid))",
            "  ==> exists-trace(event(Committed(_, eid, _))).",
        ]
    elif prop == VerificationProperty.TIMM:
        return [
            "(* Theorem 8 (TIMM): Transfer immutability *)",
            "query sk: skey, eid: entity_id;",
            "  event(Materialized(sk, eid))",
            "  ==> exists-trace(event(Committed(_, eid, _))).",
        ]
    elif prop == VerificationProperty.TSEC:
        return [
            "(* Theorem 7 (TSEC): Threshold secrecy *)",
            "(* Materialization requires key delivery *)",
            "query sk: skey, eid: entity_id;",
            "  event(Materialized(sk, eid))",
            "  ==> exists-trace(event(KeyDelivered(eid, pk(sk)))).",
        ]
    elif prop == VerificationProperty.SINT:
        return [
            "(* Theorem 4 (SINT): Shard integrity *)",
            "(* Materialized content must have been committed *)",
            "query sk: skey, eid: entity_id;",
            "  event(Materialized(sk, eid))",
            "  ==> exists-trace(event(Committed(_, eid, _))).",
        ]
    return []
